### ISSUE TITLE
how do I change the port?

### ISSUE THREAD

**Issue by languagemaniac** [jaypyles/Scraperr#15]
Hi, I need to change the default port, my port 80 is in use.

I tried changing it in the docker-compose file but I get a 404 error when I access the page.

**Comment by jaypyles** [comment]
```
traefik:
    image: traefik:latest
    container_name: traefik
    command:
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    ports:
      - <your_port_number>:80
      - 443:443
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - web
    ```
