### ISSUE TITLE
my cpu is not compatible?

### ISSUE THREAD

**Issue by languagemaniac** [jaypyles/Scraperr#17]
Hi, I changed the port as you told me but I was still geting a 404 error, so I checked logs and saw this

WARNING: MongoDB 5.0+ requires a CPU with AVX support, and your current system does not appear to have that!
  see https://jira.mongodb.org/browse/SERVER-54407
  see also https://www.mongodb.com/community/forums/t/mongodb-5-0-cpu-intel-g4650-compatibility/116610/2
  see also https://github.com/docker-library/mongo/issues/485#issuecomment-891991814

/usr/local/bin/docker-entrypoint.sh: line 416:    26 Illegal instruction     "${mongodHackedArgs[@]}" --fork

So I'm guessing I just can't run this, am I right? or is there any way to make it work? my cpu is an intel n5105

**Comment by jaypyles** [comment]
Check the "Troubleshooting" section in the README.

**Comment by languagemaniac** [comment]
> Check the "Troubleshooting" section in the README. 
> 
> Edit: you could also try downgrading the mongo version in the docker-compose.yml 

I downgraded to 4.4.7 and I don't get this issue now but still get a 404 error. Logs from scraperr and mongo look fine, traefik outputs port errors for other of my docker containers like this ""service \"tvheadend-tvheadend\" error: port is missing"" but don't think that could be causing this.

**Comment by jaypyles** [comment]
Send your compose config

**Comment by languagemaniac** [comment]
> Send your compose config 

- ```
services:
  scraperr:
    image: jpyles0524/scraperr:latest
    init: True
    build:
      context: ./
    container_name: scraperr
    env_file:
      - ./.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`${HOSTNAME}`)"
      - "traefik.http.routers.frontend.entrypoints=web" # websecure if using https
      - "traefik.http.services.frontend.loadbalancer.server.port=8000"
      # - "traefik.http.routers.frontend.tls=true"
    networks:
      - web
  traefik:
    image: traefik:latest
    container_name: traefik
    command:
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      # - "--providers.file.filename=/etc/traefik/dynamic_conf.yaml"
    ports:
      - 8124:80
      - 443:443
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      # - "./dynamic_conf.yaml:/etc/traefik/dynamic_conf.yaml"
      # - "/etc/letsencrypt/live/domain/fullchain.pem:/etc/certs/ssl-cert.pem"
      # - "/etc/letsencrypt/live/domain/privkey.pem:/etc/certs/ssl-cert.key"
    networks:
      - web
  mongo:
    container_name: webscrape-mongo
    image: mongo:4.4.7
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - web
networks:
  web:
```

**Comment by jaypyles** [comment]
You will need to set the hostname variable in the .env file to be localhost:8124, since that is what you are binding to access traefik.

**Comment by languagemaniac** [comment]
> You will need to set the hostname variable in the .env file to be localhost:8124, since that is what you are binding to access traefik. 

Unfortunately I did that but I still get a 404

HOSTNAME="localhost:8124"
HOSTNAME_DEV="localhost"

Also tried setting HOSTNAME_DEV to 8124 just for trying. Doesn't change anything (of course I'm recreating the container for every change I make but still no luck)

**Comment by jaypyles** [comment]
> > You will need to set the hostname variable in the .env file to be localhost:8124, since that is what you are binding to access traefik.
> 
> Unfortunately I did that but I still get a 404
> 
> HOSTNAME="localhost:8124" HOSTNAME_DEV="localhost"
> 
> Also tried setting HOSTNAME_DEV to 8124 just for trying. Doesn't change anything (of course I'm recreating the container for every change I make but still no luck)

If you are having such a hard time getting traefik to work in your setup, just bind the ports in the compose and skip that all together. 
```
ports:
      - 9000:8000
 ```

**Comment by languagemaniac** [comment]
> > > You will need to set the hostname variable in the .env file to be localhost:8124, since that is what you are binding to access traefik.
> > 
> > Unfortunately I did that but I still get a 404
> > 
> > HOSTNAME="localhost:8124" HOSTNAME_DEV="localhost"
> > 
> > Also tried setting HOSTNAME_DEV to 8124 just for trying. Doesn't change anything (of course I'm recreating the container for every change I make but still no luck)
> 
> If you are having such a hard time getting traefik to work in your setup, just bind the ports in the compose and skip that all together. 
> ```
> ports:
>       - 9000:8000
>  ```

I tried adding that to the ports section of the compose file and recreating, still a 404. I don't know what I'm doing wrong.

Could you please provide me with the docker compose file with the changes applied? maybe I need to edit some other thing in there?

**Comment by jaypyles** [comment]
```
scraperr:
    image: jpyles0524/scraperr:latest
    init: True
    build:
      context: ./
    container_name: scraperr
    ports:
      - 9000:8000
    env_file:
      - ./.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`${HOSTNAME}`)"
      - "traefik.http.routers.frontend.entrypoints=web" # websecure if using https
      - "traefik.http.services.frontend.loadbalancer.server.port=8000"
      # - "traefik.http.routers.frontend.tls=true"
    networks:
      - web
```
Go to localhost:9000, pulls up the App for me.
