### ISSUE TITLE
Pulls up the app, but it doesn't work

### ISSUE THREAD

**Issue by languagemaniac** [jaypyles/Scraperr#20]
Hi, sorry I might have spoken too soon in my previous issue. The app is available at localhost:9000, however, it doesn't do anything.

I can write stuff in the url; however the letters "URL" don't go away, the submit button doesn't work; the login button doesn't work, the settings button doesn't work either; I can't check the boxes...

**Comment by jaypyles** [comment]
Are you using an older browser, I know I have had issues with some apps built in newer version of Angular not working on older browsers. This could be the case, since I am developing using the newest version of Next.js.

**Comment by languagemaniac** [comment]
I'm using the latest brave browser. Also downloaded the latest chrome just in case. The only difference is that in chrome the submit button is blue, and in brave is gray.

this is my current docker compose as I understood from your previous paste, just in case I understood wrong.

```
version: '3.9' 

services:
  scraperr:
    image: jpyles0524/scraperr:latest
    init: true
    build:
      context: ./
    container_name: scraperr
    ports:
      - 9000:8000
    env_file:
      - ./.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web

networks:
  web:
  ```
  
  Or maybe I should have kept the mongo image in there? I also tried with mongo in there (don't know what I'm doing)
  
  ```
  version: '3.9' 
  
services:
   scraperr:
    image: jpyles0524/scraperr:latest
    init: true
    build:
      context: ./
    container_name: scraperr
    ports:
      - 9000:8000
    env_file:
      - ./.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web

  mongo:
    container_name: webscrape-mongo
    image: mongo:4.4.7
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - web

networks:
  web:
  ```
  
  But the result is the same
