### ISSUE TITLE
can't view logs or signup or scrape

### ISSUE THREAD

**Issue by bunkerman** [jaypyles/Scraperr#28]
Hello

I can't get it to work, the website appears, but it looks like nothing is working properly...

This is my compose file

```
services:
  scraperr:
    image: jpyles0524/scraperr:latest
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    container_name: scraperr
    command: ["npm", "run", "start"]
    environment:
      - LOG_LEVEL=DEBUG
      - NEXT_PUBLIC_API_PATH=http://scraperr_api:8000 # address to api
      - HOSTNAME="localhost"
    networks:
      default:
    ports:
      - 3003:3000
  scraperr_api:
    init: True
    image: jpyles0524/scraperr_api:latest
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    environment:
      - LOG_LEVEL=DEBUG
      - OLLAMA_URL=http://ollama:11434
      - OLLAMA_MODEL=llama3
      - MONGODB_URI=mongodb://mongodb:27017/scraperr # used to access MongoDB
      - SECRET_KEY=xxx # used to encode authentication tokens (can be a random >
      - ALGORITHM=HS256 # authentication encoding algorithm
      - ACCESS_TOKEN_EXPIRE_MINUTES=600 # access token expire minutes
    container_name: scraperr_api
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      default:
    ports:
      - 8003:8000

networks:
  default:
     external: true
```

I don't need a proxy, because I#m using it on the local network and the mongodb is running in another stack.

I cloned the repo, did make up (but had to create an empty .env file).
Is there anything I'm missing?

Thanks
