### ISSUE TITLE
Not able to install use the proivded docker-compose.xml, would u mind to provide a bit more details on how to install? Thank you

### ISSUE THREAD

**Issue by arkilis** [jaypyles/Scraperr#41]
Not able to install use the proivded docker-compose.xml, would u mind to provide a bit more details on how to install? Thank you

**Comment by opicron** [comment]
Chiming in, Im trying to run the docker compose on Synology. I got the errors Image not found, so I added the images to each section. That seemed to have fixed the issue here.

`version: '3' # Specify the version to avoid compatibility issues

services:
  scraperr:
    image: jpyles0524/scraperr
    ports:
      - "3030:3000" # Maps port 3030 on the host to port 3000 in the container    image: jpyles0524/scraperr
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.scraperr.rule=Host(`localhost`)" # change this to your domain, if not running on localhost
      - "traefik.http.routers.scraperr.entrypoints=web" # websecure if using https
      - "traefik.http.services.scraperr.loadbalancer.server.port=3000"


  scraperr_api:
    image: jpyles0524/scraperr_api
    ports:
      - "8033:8000" # Maps port 3030 on the host to port 3000 in the container    image: jpyles0524/scraperr
    environment:
      - LOG_LEVEL=INFO
      - MONGODB_URI=mongodb://root:example@mongo:27017 # used to access MongoDB
      - SECRET_KEY=your_secret_key # used to encode authentication tokens (can be a random string)
      - ALGORITHM=HS256 # authentication encoding algorithm
      - ACCESS_TOKEN_EXPIRE_MINUTES=600 # access token expire minutes
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.scraperr_api.rule=Host(`localhost`) && PathPrefix(`/api`)" # change this to your domain, if not running on localhost
      - "traefik.http.routers.scraperr_api.entrypoints=web" # websecure if using https
      - "traefik.http.middlewares.api-stripprefix.stripprefix.prefixes=/api"
      - "traefik.http.routers.scraperr_api.middlewares=api-stripprefix"
      - "traefik.http.services.scraperr_api.loadbalancer.server.port=8000"

  mongo:
    image: mongo:latest # Uses the latest MongoDB official image
    ports:
      - "27017:27017" # Maps port 27017 on the host to port 27017 in the container (default MongoDB port)
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
`

**Comment by arkilis** [comment]
@opicron Hey Mate, thanks for the compose file, I tried with that, 2 out of 3 docker are not running.

![image](https://github.com/user-attachments/assets/1d5abeac-40d0-480c-bb0c-ac430a4a178e)

**Comment by opicron** [comment]
Yeah with me the scraperr doesnt start. Checking what I did wrong.

**Comment by opicron** [comment]
Maybe use the docker config which is in the project?

```
services:
  scraperr:
    image: jpyles0524/scraperr:latest
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    container_name: scraperr
    command: ["npm", "run", "start"]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.scraperr.rule=Host(`localhost`)" # change this to your domain, if not running on localhost
      - "traefik.http.routers.scraperr.entrypoints=web" # websecure if using https
      - "traefik.http.services.scraperr.loadbalancer.server.port=3000"
    networks:
      - web
  scraperr_api:
    init: True
    image: jpyles0524/scraperr_api:latest
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    environment:
      - LOG_LEVEL=INFO
      - OLLAMA_URL=http://ollama:11434
      - OLLAMA_MODEL=phi3
      - MONGODB_URI=mongodb://root:example@webscrape-mongo:27017 # used to access MongoDB
      - SECRET_KEY=your_secret_key # used to encode authentication tokens (can be a random string)
      - ALGORITHM=HS256 # authentication encoding algorithm
      - ACCESS_TOKEN_EXPIRE_MINUTES=600 # access token expire minutes
    container_name: scraperr_api
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.scraperr_api.rule=Host(`localhost`) && PathPrefix(`/api`)" # change this to your domain, if not running on localhost
      - "traefik.http.routers.scraperr_api.entrypoints=web" # websecure if using https
      - "traefik.http.middlewares.api-stripprefix.stripprefix.prefixes=/api"
      - "traefik.http.routers.scraperr_api.middlewares=api-stripprefix"
      - "traefik.http.services.scraperr_api.loadbalancer.server.port=8000"
    networks:
      - web
  traefik:
    image: traefik:latest
    container_name: traefik
    command:
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - web
  mongo:
    container_name: webscrape-mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - web
networks:
  web:
```

Havent tried, but with traeffik it might work. Just make sure to adjust the ports for traeffik.
