### ISSUE TITLE
api container not working, sqlite crashs

### ISSUE THREAD

**Issue by Tone866** [jaypyles/Scraperr#63]
**Describe the bug**
I followed the guide and when I start the compose file, the api container outputs much errors.
I get a database file in my data folder, but it's empty.

```
Attaching to scraperr, scraperr_api
scraperr_api  | 2025-05-10 20:40:52,856 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
scraperr_api  | 2025-05-10 20:40:52,858 INFO supervisord started with pid 7
scraperr      | 
scraperr      | > webapp-template@0.1.0 start
scraperr      | > next start
scraperr      | 
scraperr      |   ▲ Next.js 14.2.4
scraperr      |   - Local:        http://localhost:3000
scraperr      | 
scraperr      |  ✓ Starting...
scraperr_api  | 2025-05-10 20:40:53,862 INFO spawned: 'api' with pid 8
scraperr_api  | 2025-05-10 20:40:53,864 INFO spawned: 'worker' with pid 9
scraperr      |  ✓ Ready in 735ms
scraperr_api  | 2025-05-10 20:40:54,866 INFO success: api entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
scraperr_api  | 2025-05-10 20:40:54,866 INFO success: worker entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
scraperr_api  | INFO:     Will watch for changes in these directories: ['/project']
scraperr_api  | INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
scraperr_api  | INFO:     Started reloader process [17] using StatReload
scraperr_api  | INFO:__main__:Starting job worker...
scraperr_api  | Traceback (most recent call last):
scraperr_api  |   File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
scraperr_api  |     return _run_code(code, main_globals, None,
scraperr_api  |   File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
scraperr_api  |     exec(code, run_globals)
scraperr_api  |   File "/project/api/backend/worker/job_worker.py", line 50, in <module>
scraperr_api  |     asyncio.run(main())
scraperr_api  |   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
scraperr_api  |     return loop.run_until_complete(main)
scraperr_api  |   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
scraperr_api  |     return future.result()
scraperr_api  |   File "/project/api/backend/worker/job_worker.py", line 45, in main
scraperr_api  |     await process_job()
scraperr_api  |   File "/project/api/backend/worker/job_worker.py", line 16, in process_job
scraperr_api  |     job = await get_queued_job()
scraperr_api  |   File "/project/api/backend/job/job.py", line 39, in get_queued_job
scraperr_api  |     res = common_query(query)
scraperr_api  |   File "/project/api/backend/database/common.py", line 44, in query
scraperr_api  |     _ = cursor.execute(query)
scraperr_api  | sqlite3.OperationalError: no such table: jobs
scraperr_api  | 2025-05-10 20:40:57,453 WARN exited: worker (exit status 1; not expected)
scraperr_api  | INFO:     Started server process [19]
scraperr_api  | INFO:     Waiting for application startup.
scraperr_api  | 2025-05-10 20:40:58,191 INFO spawned: 'worker' with pid 21
scraperr_api  | ERROR:    Traceback (most recent call last):
scraperr_api  |   File "/project/__pypackages__/3.10/lib/starlette/routing.py", line 692, in lifespan
scraperr_api  |     async with self.lifespan_context(app) as maybe_state:
scraperr_api  |   File "/usr/local/lib/python3.10/contextlib.py", line 199, in __aenter__
scraperr_api  |     return await anext(self.gen)
scraperr_api  |   File "/project/__pypackages__/3.10/lib/fastapi/routing.py", line 133, in merged_lifespan
scraperr_api  |     async with original_context(app) as maybe_original_state:
scraperr_api  |   File "/usr/local/lib/python3.10/contextlib.py", line 199, in __aenter__
scraperr_api  |     return await anext(self.gen)
scraperr_api  |   File "/project/__pypackages__/3.10/lib/fastapi/routing.py", line 133, in merged_lifespan
scraperr_api  |     async with original_context(app) as maybe_original_state:
scraperr_api  |   File "/usr/local/lib/python3.10/contextlib.py", line 199, in __aenter__
scraperr_api  |     return await anext(self.gen)
scraperr_api  |   File "/project/__pypackages__/3.10/lib/fastapi/routing.py", line 133, in merged_lifespan
scraperr_api  |     async with original_context(app) as maybe_original_state:
scraperr_api  |   File "/usr/local/lib/python3.10/contextlib.py", line 199, in __aenter__
scraperr_api  |     return await anext(self.gen)
scraperr_api  |   File "/project/__pypackages__/3.10/lib/fastapi/routing.py", line 133, in merged_lifespan
scraperr_api  |     async with original_context(app) as maybe_original_state:
scraperr_api  |   File "/usr/local/lib/python3.10/contextlib.py", line 199, in __aenter__
scraperr_api  |     return await anext(self.gen)
scraperr_api  |   File "/project/__pypackages__/3.10/lib/fastapi/routing.py", line 133, in merged_lifespan
scraperr_api  |     async with original_context(app) as maybe_original_state:
scraperr_api  |   File "/project/__pypackages__/3.10/lib/starlette/routing.py", line 569, in __aenter__
scraperr_api  |     await self._router.startup()
scraperr_api  |   File "/project/__pypackages__/3.10/lib/starlette/routing.py", line 669, in startup
scraperr_api  |     await handler()
scraperr_api  |   File "/project/api/backend/app.py", line 57, in startup_event
scraperr_api  |     start_cron_scheduler(scheduler)
scraperr_api  |   File "/project/api/backend/job/cron_scheduling/cron_scheduling.py", line 86, in start_cron_scheduler
scraperr_api  |     cron_jobs = get_all_cron_jobs()
scraperr_api  |   File "/project/api/backend/job/cron_scheduling/cron_scheduling.py", line 52, in get_all_cron_jobs
scraperr_api  |     cron_jobs = query("SELECT * FROM cron_jobs")
scraperr_api  |   File "/project/api/backend/database/common.py", line 44, in query
scraperr_api  |     _ = cursor.execute(query)
scraperr_api  | sqlite3.OperationalError: no such table: cron_jobs
scraperr_api  | 
scraperr_api  | ERROR:    Application startup failed. Exiting.
scraperr_api  | 2025-05-10 20:40:59,196 INFO success: worker entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
scraperr_api  | INFO:__main__:Starting job worker...
scraperr_api  | Traceback (most recent call last):
scraperr_api  |   File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
scraperr_api  |     return _run_code(code, main_globals, None,
scraperr_api  |   File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
scraperr_api  |     exec(code, run_globals)
scraperr_api  |   File "/project/api/backend/worker/job_worker.py", line 50, in <module>
scraperr_api  |     asyncio.run(main())
scraperr_api  |   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
scraperr_api  |     return loop.run_until_complete(main)
scraperr_api  |   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
scraperr_api  |     return future.result()
scraperr_api  |   File "/project/api/backend/worker/job_worker.py", line 45, in main
scraperr_api  |     await process_job()
scraperr_api  |   File "/project/api/backend/worker/job_worker.py", line 16, in process_job
scraperr_api  |     job = await get_queued_job()
scraperr_api  |   File "/project/api/backend/job/job.py", line 39, in get_queued_job
scraperr_api  |     res = common_query(query)
scraperr_api  |   File "/project/api/backend/database/common.py", line 44, in query
scraperr_api  |     _ = cursor.execute(query)
scraperr_api  | sqlite3.OperationalError: no such table: jobs
scraperr_api  | 2025-05-10 20:41:01,897 WARN exited: worker (exit status 1; not expected)
scraperr_api  | 2025-05-10 20:41:02,900 INFO spawned: 'worker' with pid 26
scraperr_api  | 2025-05-10 20:41:03,902 INFO success: worker entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

```
services:
  scraperr:
    depends_on:
      - scraperr_api
    image: jpyles0524/scraperr:latest
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    container_name: scraperr
    command: ["npm", "run", "start"]
    environment:
      - NEXT_PUBLIC_API_URL=http://domain:8000 # your API URL
      - SERVER_URL=http://scraperr_api:8000 # your docker container API URL
    ports:
      - 80:3000
    networks:
      - web
  scraperr_api:
    init: True
    image: jpyles0524/scraperr_api:latest
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    environment:
      - LOG_LEVEL=INFO
      - SECRET_KEY=key # used to encode authentication tokens (can be a random string)
      - ALGORITHM=HS256 # authentication encoding algorithm
      - ACCESS_TOKEN_EXPIRE_MINUTES=600 # access token expire minutes
    hostname: scraperr_api
    container_name: scraperr_api
    ports:
      - 8000:8000
    volumes:
      - "./data:/project/data"
      - "./media:/project/media"
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web
networks:
  web:
```
